### ISSUE TITLE
how to use it with React

### ISSUE THREAD

**Issue by a-m-dev** [mapbox/mapbox-icu-js#11]
hello
how can i use this plugin with react ?????

**Comment by a-m-dev** [comment]
i solved it like this 👍 



```
import React from "react";
import ReactDOM from "react-dom";
import "./styles.css";
import ReactMapboxGl, { Layer, Feature } from "react-mapbox-gl";

// by adding this two lines , make sure to install mapbox-gl 
import { setRTLTextPlugin } from "mapbox-gl";
setRTLTextPlugin("https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-rtl-text/v0.1.2/mapbox-gl-rtl-text.js");

....

```

**Comment by dannykennedy** [comment]
This solution doesn't work for me when using custom labels (symbols) via the `<Source>` and `<Layer>` components.

**Comment by ryanhamley** [comment]
@dannykennedy This might be a better question for [react-mapbox-gl](https://github.com/alex3165/react-mapbox-gl). We don't maintain that library and I'm not sure how this plugin may interact with it. If you need further assistance on our side, contact [Mapbox Support](https://support.mapbox.com/hc/en-us).
