### ISSUE TITLE
UMD export for use without mapbox

### ISSUE THREAD

**Issue by w8r** [mapbox/mapbox-icu-js#13]
We are trying to use your module as a plugin to our library, and we would like to be able to use it as a drop-in add-on in the browser as well, but index.js assumes Node.js/CommonJS environment.

I added a PR #12 that does it, but didn't re-build the library to avoid unnecessary diffs.

Thanks a lot for the great library.

**Comment by ChrisLoer** [comment]
Fixed with PR #14.
