### ISSUE TITLE
can not load plugin from local storage

### ISSUE THREAD

**Issue by kavehcs** [mapbox/mapbox-icu-js#23]
Refused to execute script from 'http://127.0.0.1:8000/static/mapbox/mapbox-gl-rtl-text.js' because its MIME type ('text/plain') is not executable.
![Capture](https://user-images.githubusercontent.com/27343530/65827815-08fe3400-e2a1-11e9-89c1-1583fda26375.PNG)
![Capture01](https://user-images.githubusercontent.com/27343530/65828662-2daad980-e2aa-11e9-82e7-aea39cd48b0f.PNG)

**Comment by kavehcs** [comment]
![Capture01](https://user-images.githubusercontent.com/27343530/65828646-018f5880-e2aa-11e9-98cc-f085a5edebd9.PNG)

**Comment by asheemmamoowala** [comment]
@kavehcs This seems like an issue with the MIME type used to serve the plugin from your local static server. Feel free to reopen with a reproducible case if this happen seven with the hosted plugin at https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-rtl-text/v0.2.3/mapbox-gl-rtl-text.js
