### ISSUE TITLE
Bad mapbox-gl dependency version documentation

### ISSUE THREAD

**Issue by Danysan1** [mapbox/mapbox-icu-js#27]
[README.md](../blob/main/README.md) says that this package "Requires `mapbox-gl-js` (version 0.32.1 and up).". 

[package.json](../blob/main/package.json) however has a dependency to `mapbox-gl` >=0.32.1 <2.0.0:

```json
  "peerDependencies": {
    "mapbox-gl": ">=0.32.1 <2.0.0"
  },
```

Since the latest version of `mapbox-gl` is 2.5.1, this dependency breaks a standard installation and should be documented in the README .

Of course it would be even better if any incompatibility with `mapbox-gl` >= 2.0.0 was solved and this dependency was changed.
If it can be of any help some days ago I installed `mapbox-gl-rtl-text` 0.2.3 together with `mapbox-gl` 2.5.1 using `--force` in https://www.dsantini.it/etymology and as of now I haven't encountered problems.

**Comment by fxi** [comment]
Hello !

Any news on this ? We use the `--legacy-peer-deps` workaround since a while, but it does not feel right on the long run.

Thanks !

**Comment by sven-meyer-wetter-com** [comment]
Any news on that?
